### ISSUE TITLE
MultiSEAM加到yolov7中报错

### ISSUE THREAD

**Issue by gitdjz** [Krasjet-Yu/YOLO-FaceV2#32]
大佬，这是咋回事啊？
Traceback (most recent call last):
  File "D:\PycharmProjects\yolov7\models\yolo.py", line 892, in <module>
    model = Model(opt.cfg).to(device)
  File "D:\PycharmProjects\yolov7\models\yolo.py", line 547, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "D:\PycharmProjects\yolov7\models\yolo.py", line 602, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "D:\PycharmProjects\yolov7\models\yolo.py", line 628, in forward_once
    x = m(x)  # run
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PycharmProjects\yolov7\models\common.py", line 3033, in forward
    y0 = self.DCovN0(x)
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\modules\batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\functional.py", line 2419, in batch_norm
    _verify_batch_size(input.size())
  File "D:\condaenv\pytorch\lib\site-packages\torch\nn\functional.py", line 2387, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

**Comment by liiicon** [comment]
请问你解决了嘛
