### ISSUE TITLE
训练时遇到的错误！

### ISSUE THREAD

**Issue by sunmooncode** [Krasjet-Yu/YOLO-FaceV2#5]
```
Traceback (most recent call last):
  File "train.py", line 555, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 377, in train
    is_coco=is_coco)
  File "/home/Face/YOLO-FaceV2/test.py", line 115, in test
    loss += compute_loss([x.float() for x in train_out], targets)[1][:5]  # box, obj, cls
  File "/home/Face/YOLO-FaceV2/utils/loss.py", line 224, in __call__
    dic[int(value)].append(indexs)
KeyError: 32
```
训练的时候双卡跑会出现 ，单卡跑的时候就会出现上面错误！

**Comment by sunmooncode** [comment]
当我把batch-size设置为16的时候能够正常运行~

**Comment by sunmooncode** [comment]
![image](https://user-images.githubusercontent.com/86471590/184073199-85d66181-2521-403d-9c77-7b5e6746b58f.png)
训练过程中lcls会变成nan，是pytorch版本的问题嘛？

**Comment by Krasjet-Yu** [comment]
因为你增加了landmark损失，一些超参数需要重新调节

**Comment by sunmooncode** [comment]
@Krasjet-Yu 
![image](https://user-images.githubusercontent.com/86471590/184078560-f472d8cb-3b47-4165-99e8-2b3bb8084937.png)
这个是在我笔记本训练的 没有nan 同样的超参数！

上面那个keyerror有什么建议嘛

**Comment by Krasjet-Yu** [comment]
我没试过双卡训练。我后续试一下双卡解决一下bug。不过单卡的话batch16，epoch200差不多也就一天左右吧。

**Comment by sunmooncode** [comment]
@Krasjet-Yu  好的  感谢 我在调一调试试~~

**Comment by shituo123456** [comment]
> @Krasjet-Yu 好的 感谢 我在调一调试试~~

你好 keyerror解决了吗

**Comment by shituo123456** [comment]
DDP  4卡训练 batch100就报错   改成64好了
